### ISSUE TITLE
File::Listing 6.09_01: Introduction of test dependency LWP::Simple causes dependency loop

### ISSUE THREAD

**Issue by dbevans** [PerlAlien/File-Listing#19]
This is because libwww-perl, which provides LWP::Simple, itself depends on File::Listing.  Running t/apache.t only needs it if 
--update is applied so perhaps it should be made a soft dependency and skip apache.t if updating and LWP::Simple is not available.

**Comment by exodist** [comment]
This issue is preventing me from doing some downstream testing I do before releasing Test-Simple versions. Would appreciate a fix asap, thanks!

**Comment by plicease** [comment]
I'm sorry I missed this before going to prod 6.10.  It's been fixed in 6.11.

**Comment by ComaVN** [comment]
Awesome, thanks for the incredibly speedy response!

(oh, and if someone's mirror takes a while to catch up: doing `cpanm --notest File::Listing` works as a workaround)

**Comment by plicease** [comment]
As part of the post Morton on this I realized I wasn't getting some of the usual notifications for the `PerlAlien` GitHub organization.  I've updated this to make sure that I don't miss critical tickets before production deploys!
